export const APPLICATION_IS_LOADING = 'APPLICATION_IS_LOADING';
export const APPLICATION_IS_NOT_LOADING = 'APPLICATION_IS_NOT_LOADING';

export const APPLICATION_SET_TEMP_SEARCH_TEXT =
  'APPLICATION_SET_TEMP_SEARCH_TEXT';
export const APPLICATION_SET_SEARCH_TEXT = 'APPLICATION_SET_SEARCH_TEXT';
